---
name: MarkdownLint

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
    paths:
      - "**.md"

  pull_request:

jobs:
  lint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'
