---
name: Python Checks

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "**.pyi"

  pull_request:
  workflow_dispatch:

jobs:
  black-linter:
    name: Black linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Black check
        uses: psf/black@stable
        with:
          options: "--check --verbose"

  mypy:
    name: MyPy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Pip install dependencies
        run: pip install mypy -r requirements.txt

      - name: MyPy check
        run: MYPYPATH="stubs" mypy app/
